version: '3.1'

services:
  crediplus:
    build:
      context: ./BackEnd
    image: mcr.microsoft.com/dotnet/samples:aspnetapp
    container_name: crediplus_api
    restart: always
    ports:
      - 7070:9070
    environment:
      - TZ=America/Bogota
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:9070
  pirawash-front:
    build:
      context: ./FrontEnd
    container_name: crediplus_front
    restart: always
    ports:
      - 7071:80
