version: '3.1'

services:
  crediplus_api:
    build:
      context: ./BackEnd
    image: mcr.microsoft.com/dotnet/samples:aspnetapp
    container_name: crediplus_api
    restart: always
    ports:
      - 7070:9070
    environment:
      - TZ=America/Bogota
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
  